import 'dart:ui';
import 'package:e_commerce/feature/home/models/modelproduct.dart';

// ==================== ALL PRODUCTS ====================
List<ProductModel> products = [
  // ==================== SHOES ====================
  ProductModel(
    id: "1",
    type: "Shoes",
    name: "Nike Air Max",
    prands: "Nike",
    description: "Comfortable running shoes with air cushion technology.",
    image:
        "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    price: 120,
    rating: 4.5,
    numrating: 120,
    category: "Shoes",
    onstack: "In Stock",
    stock: 15,
    color: const Color(0xFFE53935),
    material: "Premium mesh upper, rubber sole",
    weight: "280g (size M)",
    waterproof: "Yes — IPX4 rated",
    origin: "Vietnam",
    sku: "NK-AMP-2026-BLK",
  ),
  ProductModel(
    id: "2",
    type: "Shoes",
    name: "Adidas Superstar",
    prands: "Adidas",
    description: "Iconic streetwear sneakers with rubber shell toe.",
    image:
        "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&q=80",
    price: 100,
    rating: 4.7,
    numrating: 200,
    category: "Shoes",
    onstack: "In Stock",
    stock: 20,
    color: const Color(0xFF212121),
    material: "Full-grain leather, rubber cupsole",
    weight: "340g (size M)",
    waterproof: "Water-resistant coating",
    origin: "Indonesia",
    sku: "AD-SST-2026-WHT",
  ),
  ProductModel(
    id: "3",
    type: "Shoes",
    name: "Puma Classic Suede",
    prands: "Puma",
    description: "Retro street style low-top sneakers in premium suede.",
    image:
        "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80",
    price: 75,
    rating: 4.4,
    numrating: 95,
    category: "Shoes",
    onstack: "In Stock",
    stock: 18,
    color: const Color(0xFF1E88E5),
    material: "100% Suede leather, synthetic lining",
    weight: "310g (size M)",
    waterproof: "No",
    origin: "Vietnam",
    sku: "PM-CS-2026-RED",
  ),
  ProductModel(
    id: "4",
    type: "Shoes",
    name: "New Balance 574",
    prands: "New Balance",
    description: "Versatile everyday sneaker engineered for all-day comfort.",
    image:
        "https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&q=80",
    price: 85,
    rating: 4.6,
    numrating: 140,
    category: "Shoes",
    onstack: "In Stock",
    stock: 22,
    color: const Color(0xFF78909C),
    material: "Suede / Mesh upper, ENCAP midsole",
    weight: "295g (size M)",
    waterproof: "No",
    origin: "China",
    sku: "NB-574-2026-NVY",
  ),

  // ==================== TECH ====================
  ProductModel(
    id: "5",
    type: "Tech",
    name: "iPhone 15 Pro",
    prands: "Apple",
    description: "Titanium design, A17 Pro chip, advanced 48MP camera system.",
    image:
        "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80",
    price: 999,
    rating: 4.9,
    numrating: 320,
    category: "Tech",
    onstack: "In Stock",
    stock: 10,
    color: const Color(0xFF37474F),
    material: "Grade 5 Titanium frame, Ceramic Shield front",
    weight: "187g",
    waterproof: "Yes — IP68 rated",
    origin: "China",
    sku: "APL-IP15P-256",
  ),
  ProductModel(
    id: "6",
    type: "Tech",
    name: "Galaxy S24 Ultra",
    prands: "Samsung",
    description: "Galaxy AI powered smartphone with 200MP camera and S-Pen.",
    image:
        "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80",
    price: 899,
    rating: 4.8,
    numrating: 180,
    category: "Tech",
    onstack: "In Stock",
    stock: 12,
    color: const Color(0xFF5C6BC0),
    material: "Titanium frame, Gorilla Armor glass",
    weight: "232g",
    waterproof: "Yes — IP68 rated",
    origin: "South Korea",
    sku: "SAM-S24U-512",
  ),
  ProductModel(
    id: "7",
    type: "Tech",
    name: "Sony WH-1000XM5",
    prands: "Sony",
    description: "Industry-leading noise canceling wireless headphones.",
    image:
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    price: 349,
    rating: 4.9,
    numrating: 410,
    category: "Tech",
    onstack: "In Stock",
    stock: 25,
    color: const Color(0xFF263238),
    material: "Soft fit synthetic leather, ABS plastic",
    weight: "250g",
    waterproof: "No",
    origin: "Malaysia",
    sku: "SNY-XM5-BLK",
  ),
  ProductModel(
    id: "8",
    type: "Tech",
    name: "Apple Watch Series 9",
    prands: "Apple",
    description:
        "Advanced health sensors, bright display, and double tap gesture.",
    image:
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
    price: 399,
    rating: 4.7,
    numrating: 215,
    category: "Tech",
    onstack: "In Stock",
    stock: 14,
    color: const Color(0xFFF48FB1),
    material: "100% Recycled Aluminum, Ion-X glass",
    weight: "38.7g",
    waterproof: "Yes — WR50 (50m)",
    origin: "China",
    sku: "APL-W9-45MM",
  ),
  ProductModel(
    id: "9",
    type: "Tech",
    name: "Logitech MX Master 3S",
    prands: "Logitech",
    description: "Ergonomic wireless mouse with ultra-fast MagSpeed scrolling.",
    image:
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80",
    price: 99,
    rating: 4.8,
    numrating: 290,
    category: "Tech",
    onstack: "In Stock",
    stock: 30,
    color: const Color(0xFF424242),
    material: "Textured rubber grip, PCR plastic",
    weight: "141g",
    waterproof: "No",
    origin: "China",
    sku: "LOG-MX3S-GRY",
  ),

  // ==================== FASHION ====================
  ProductModel(
    id: "10",
    type: "Fashion",
    name: "Classic Silk Dress",
    prands: "Zara",
    description: "Elegant evening midi dress made with premium silk fabric.",
    image:
        "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80",
    price: 89,
    rating: 4.4,
    numrating: 90,
    category: "Fashion",
    onstack: "In Stock",
    stock: 25,
    color: const Color(0xFF880E4F),
    material: "95% Pure Mulberry Silk, 5% Elastane",
    weight: "190g",
    waterproof: "No",
    origin: "Italy",
    sku: "ZR-SLK-DRS-01",
  ),
  ProductModel(
    id: "11",
    type: "Fashion",
    name: "Vintage Denim Jacket",
    prands: "Levi's",
    description: "Original trucker denim jacket with durable cotton fabric.",
    image:
        "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&q=80",
    price: 79,
    rating: 4.6,
    numrating: 115,
    category: "Fashion",
    onstack: "In Stock",
    stock: 18,
    color: const Color(0xFF1565C0),
    material: "100% Heavyweight Cotton Denim",
    weight: "650g",
    waterproof: "No",
    origin: "Mexico",
    sku: "LEV-TRK-JKT-BLU",
  ),
  ProductModel(
    id: "12",
    type: "Fashion",
    name: "Oversized Cotton Hoodie",
    prands: "H&M",
    description: "Comfortable heavyweight fleece pullover hoodie.",
    image:
        "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&q=80",
    price: 45,
    rating: 4.5,
    numrating: 160,
    category: "Fashion",
    onstack: "In Stock",
    stock: 40,
    color: const Color(0xFFD7CCC8),
    material: "80% Organic Cotton, 20% Polyester",
    weight: "480g",
    waterproof: "No",
    origin: "Turkey",
    sku: "HM-OVS-HD-BEG",
  ),
  ProductModel(
    id: "13",
    type: "Fashion",
    name: "Classic Leather Watch",
    prands: "Fossil",
    description:
        "Minimalist stainless steel quartz watch with brown leather strap.",
    image:
        "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80",
    price: 110,
    rating: 4.7,
    numrating: 78,
    category: "Fashion",
    onstack: "In Stock",
    stock: 15,
    color: const Color(0xFF5D4037),
    material: "Stainless steel case, genuine leather strap",
    weight: "72g",
    waterproof: "Yes — 5 ATM (50m)",
    origin: "Japan",
    sku: "FSL-CL-WCH-BRN",
  ),

  // ==================== HOME ====================
  ProductModel(
    id: "14",
    type: "Home",
    name: "Minimalist Desk Lamp",
    prands: "IKEA",
    description: "Modern adjustable LED desk light with warm atmosphere.",
    image:
        "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80",
    price: 35,
    rating: 4.3,
    numrating: 70,
    category: "Home",
    onstack: "In Stock",
    stock: 30,
    color: const Color(0xFFFFB300),
    material: "Powder-coated steel, Aluminum",
    weight: "920g",
    waterproof: "No — Indoor use only",
    origin: "Poland",
    sku: "IKA-MIN-LMP-WHT",
  ),
  ProductModel(
    id: "15",
    type: "Home",
    name: "Ceramic Coffee Mug Set",
    prands: "Zara Home",
    description: "Handcrafted matte finish ceramic mugs, pack of 4.",
    image:
        "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80",
    price: 28,
    rating: 4.8,
    numrating: 130,
    category: "Home",
    onstack: "In Stock",
    stock: 50,
    color: const Color(0xFF8D6E63),
    material: "High-fired stoneware ceramic",
    weight: "1.2kg (Set)",
    waterproof: "Yes — Dishwasher safe",
    origin: "Portugal",
    sku: "ZH-MUG-SET-MAT",
  ),
  ProductModel(
    id: "16",
    type: "Home",
    name: "Aroma Diffuser & Humidifier",
    prands: "Philips",
    description:
        "Ultrasonic cool mist essential oil diffuser with ambient light.",
    image:
        "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80",
    price: 49,
    rating: 4.6,
    numrating: 110,
    category: "Home",
    onstack: "In Stock",
    stock: 20,
    color: const Color(0xFFE0E0E0),
    material: "BPA-Free PP & ABS plastic, Wood grain finish",
    weight: "430g",
    waterproof: "Water basin leak-proof",
    origin: "China",
    sku: "PHL-ARM-DIF-500",
  ),

  // ==================== BEAUTY ====================
  ProductModel(
    id: "17",
    type: "Beauty",
    name: "Hydrating Face Cream",
    prands: "L'Oreal",
    description: "Daily moisturizing cream enriched with hyaluronic acid.",
    image:
        "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    price: 32,
    rating: 4.6,
    numrating: 150,
    category: "Beauty",
    onstack: "In Stock",
    stock: 40,
    color: const Color(0xFF80DEEA),
    material: "Hyaluronic acid, Ceramides, Vitamin E",
    weight: "50ml (140g jar)",
    waterproof: "No",
    origin: "France",
    sku: "LOR-HYD-CRM-50M",
  ),
  ProductModel(
    id: "18",
    type: "Beauty",
    name: "Luxury Eau De Parfum",
    prands: "Chanel",
    description: "Long-lasting floral and woody fragrance for men and women.",
    image:
        "https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80",
    price: 135,
    rating: 4.9,
    numrating: 230,
    category: "Beauty",
    onstack: "In Stock",
    stock: 12,
    color: const Color(0xFFFFD54F),
    material: "Pure fragrance oils, Ethanol, Glass flacon",
    weight: "100ml (320g bottle)",
    waterproof: "Sealed flacon",
    origin: "France",
    sku: "CHN-EDP-100-LUX",
  ),
  ProductModel(
    id: "19",
    type: "Beauty",
    name: "Vitamin C Glow Serum",
    prands: "The Ordinary",
    description: "Brightening antioxidant serum for radiant, even skin tone.",
    image:
        "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80",
    price: 24,
    rating: 4.7,
    numrating: 310,
    category: "Beauty",
    onstack: "In Stock",
    stock: 45,
    color: const Color(0xFFFF9800),
    material: "Ascorbic Acid 8%, Alpha Arbutin 2%",
    weight: "30ml (95g)",
    waterproof: "No",
    origin: "Canada",
    sku: "ORD-VTC-SRM-30",
  ),

  // ==================== SPORTS ====================
  ProductModel(
    id: "20",
    type: "Sports",
    name: "Match Pro Football",
    prands: "Adidas",
    description:
        "Thermal bonded seamless surface for more predictable trajectory.",
    image:
        "https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?w=800&q=80",
    price: 35,
    rating: 4.7,
    numrating: 130,
    category: "Sports",
    onstack: "In Stock",
    stock: 25,
    color: const Color(0xFF43A047),
    material: "100% TPU cover, Butyl bladder",
    weight: "430g (Size 5)",
    waterproof: "Yes — Seamless water barrier",
    origin: "Pakistan",
    sku: "AD-FTB-MCH-SZ5",
  ),
  ProductModel(
    id: "21",
    type: "Sports",
    name: "Insulated Sports Bottle",
    prands: "Hydro Flask",
    description:
        "Double-wall vacuum stainless steel water bottle keeps cold 24h.",
    image:
        "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80",
    price: 29,
    rating: 4.9,
    numrating: 420,
    category: "Sports",
    onstack: "In Stock",
    stock: 50,
    color: const Color(0xFF00ACC1),
    material: "18/8 Pro-Grade Stainless Steel",
    weight: "375g",
    waterproof: "100% Leak-Proof Cap",
    origin: "USA",
    sku: "HF-BTL-32OZ-BLK",
  ),
  ProductModel(
    id: "22",
    type: "Sports",
    name: "Non-Slip Yoga Mat",
    prands: "Nike",
    description: "Eco-friendly high density cushioning exercise workout mat.",
    image:
        "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80",
    price: 38,
    rating: 4.5,
    numrating: 95,
    category: "Sports",
    onstack: "In Stock",
    stock: 30,
    color: const Color(0xFF8E24AA),
    material: "Eco-TPE (Thermoplastic Elastomer)",
    weight: "850g",
    waterproof: "Yes — Sweat resistant",
    origin: "Taiwan",
    sku: "NK-YGA-MAT-6MM",
  ),

  // ==================== BOOKS ====================
  ProductModel(
    id: "23",
    type: "Books",
    name: "Flutter in Action",
    prands: "Manning",
    description: "Complete guide to building beautiful cross-platform apps.",
    image:
        "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80",
    price: 42,
    rating: 4.9,
    numrating: 200,
    category: "Books",
    onstack: "In Stock",
    stock: 15,
    color: const Color(0xFF0288D1),
    material: "Acid-free paper, Softcover binding",
    weight: "620g",
    waterproof: "No",
    origin: "USA",
    sku: "BK-FLT-ACT-2026",
  ),
  ProductModel(
    id: "24",
    type: "Books",
    name: "Clean Code",
    prands: "Prentice Hall",
    description:
        "A handbook of agile software craftsmanship by Robert C. Martin.",
    image:
        "https://images.unsplash.com/photo-1532012164546-f432f2e3edd4?w=800&q=80",
    price: 38,
    rating: 4.8,
    numrating: 540,
    category: "Books",
    onstack: "In Stock",
    stock: 20,
    color: const Color(0xFF455A64),
    material: "Recycled fine print paper, Hardcover",
    weight: "740g",
    waterproof: "No",
    origin: "USA",
    sku: "BK-CLN-COD-PRN",
  ),
  ProductModel(
    id: "25",
    type: "Books",
    name: "Atomic Habits",
    prands: "Penguin",
    description:
        "An easy and proven way to build good habits and break bad ones.",
    image:
        "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&q=80",
    price: 22,
    rating: 4.9,
    numrating: 890,
    category: "Books",
    onstack: "In Stock",
    stock: 60,
    color: const Color(0xFFF57C00),
    material: "Standard offset paper, Paperback",
    weight: "320g",
    waterproof: "No",
    origin: "UK",
    sku: "BK-ATM-HBT-PNG",
  ),

  // ==================== TOYS ====================
  ProductModel(
    id: "26",
    type: "Toys",
    name: "Classic Soft Teddy Bear",
    prands: "Kids Toys",
    description: "Ultra-plush huggable brown teddy bear safe for all ages.",
    image:
        "https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&q=80",
    price: 25,
    rating: 4.6,
    numrating: 85,
    category: "Toys",
    onstack: "In Stock",
    stock: 35,
    color: const Color(0xFFA1887F),
    material: "100% Polyester plush, PP cotton fill",
    weight: "220g",
    waterproof: "No — Surface washable",
    origin: "Vietnam",
    sku: "TY-TED-BEAR-30CM",
  ),
  ProductModel(
    id: "27",
    type: "Toys",
    name: "Speed RC Drift Car",
    prands: "Lego Group",
    description:
        "High speed 2.4GHz remote control racing car with LED headlights.",
    image:
        "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&q=80",
    price: 54,
    rating: 4.5,
    numrating: 110,
    category: "Toys",
    onstack: "In Stock",
    stock: 16,
    color: const Color(0xFFD32F2F),
    material: "ABS anti-collision plastic, Rubber tires",
    weight: "580g",
    waterproof: "Splash-proof chassis",
    origin: "China",
    sku: "TY-RC-DRF-24G",
  ),
  ProductModel(
    id: "28",
    type: "Toys",
    name: "Space Shuttle Building Bricks",
    prands: "Lego",
    description: "Creative spaceship construction kit with astronaut figures.",
    image:
        "https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=800&q=80",
    price: 65,
    rating: 4.9,
    numrating: 175,
    category: "Toys",
    onstack: "In Stock",
    stock: 19,
    color: const Color(0xFFFBC02D),
    material: "Non-toxic High precision ABS plastic",
    weight: "890g (Boxed)",
    waterproof: "Yes — Washable bricks",
    origin: "Denmark",
    sku: "LG-SPC-SHT-860P",
  ),
];

// ==================== FLASH SALE ====================
List<ProductModel> flashSale = [
  ProductModel(
    id: "1",
    type: "Flash Sale",
    name: "Wireless Headphones",
    prands: "JBL",
    description: "High quality wireless headphones with clear sound.",
    image:
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    price: 45.99,
    rating: 4.5,
    numrating: 120,
    category: "Electronics",
    onstack: "In Stock",
    stock: 20,
    color: const Color(0xFFFF5722),
    material: "Engineered polymer & cushioned ear pads",
    weight: "220g",
    waterproof: "Sweat-resistant",
    origin: "Vietnam",
    sku: "JBL-WHP-500BT",
  ),
  ProductModel(
    id: "2",
    type: "Flash Sale",
    name: "Smart Watch",
    prands: "Apple",
    description: "Modern smart watch with health and fitness features.",
    image:
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80",
    price: 39.99,
    rating: 4.3,
    numrating: 85,
    category: "Electronics",
    onstack: "In Stock",
    stock: 15,
    color: const Color(0xFF00B0FF),
    material: "Aluminum case, Fluoroelastomer sport band",
    weight: "36g",
    waterproof: "Yes — IP68 rated",
    origin: "China",
    sku: "APL-SMW-SE-BLU",
  ),
  ProductModel(
    id: "3",
    type: "Flash Sale",
    name: "Running Shoes",
    prands: "Nike",
    description: "Comfortable running shoes for sports and daily use.",
    image:
        "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    price: 55.00,
    rating: 4.7,
    numrating: 210,
    category: "Shoes",
    onstack: "In Stock",
    stock: 30,
    color: const Color(0xFFFF1744),
    material: "Breathable knit mesh, EVA foam sole",
    weight: "260g (size M)",
    waterproof: "No",
    origin: "Vietnam",
    sku: "NK-RNS-RN4-RED",
  ),
  ProductModel(
    id: "101",
    type: "Flash Sale",
    name: "Outdoor Bluetooth Speaker",
    prands: "Anker",
    description:
        "IPX7 waterproof portable speaker with rich bass and 24h playtime.",
    image:
        "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80",
    price: 29.99,
    rating: 4.6,
    numrating: 140,
    category: "Electronics",
    onstack: "In Stock",
    stock: 25,
    color: const Color(0xFF00E676),
    material: "Rugged rubberized housing, metallic mesh",
    weight: "360g",
    waterproof: "Yes — IPX7 waterproof",
    origin: "China",
    sku: "ANK-SPK-SC2-GRN",
  ),
  ProductModel(
    id: "102",
    type: "Flash Sale",
    name: "Aviator Sunglasses",
    prands: "Ray-Ban",
    description:
        "Classic metal frame sunglasses with 100% UV polarized lenses.",
    image:
        "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80",
    price: 49.00,
    rating: 4.8,
    numrating: 110,
    category: "Accessories",
    onstack: "In Stock",
    stock: 18,
    color: const Color(0xFFFFD700),
    material: "Gold-plated metal alloy frame, Glass lenses",
    weight: "31g",
    waterproof: "Yes — Corrosion resistant",
    origin: "Italy",
    sku: "RB-AVT-3025-GLD",
  ),
  ProductModel(
    id: "103",
    type: "Flash Sale",
    name: "Fast Dual Car Charger",
    prands: "Baseus",
    description: "65W USB-C fast charging adapter with smart LED display.",
    image:
        "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80",
    price: 15.99,
    rating: 4.4,
    numrating: 95,
    category: "Accessories",
    onstack: "In Stock",
    stock: 50,
    color: const Color(0xFF37474F),
    material: "Fireproof PC & Aluminum alloy",
    weight: "45g",
    waterproof: "No",
    origin: "China",
    sku: "BAS-CHG-65W-CC",
  ),
];

// ==================== RECOMMENDED PRODUCTS ====================
List<ProductModel> recommendedProducts = [
  ProductModel(
    id: "4",
    type: "Recommended",
    name: "Mechanical Gaming Keyboard",
    prands: "Logitech",
    description: "RGB backlit mechanical keyboard with fast tactile switches.",
    image:
        "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80",
    price: 69.99,
    rating: 4.8,
    numrating: 340,
    category: "Electronics",
    onstack: "In Stock",
    stock: 25,
    color: const Color(0xFF3F51B5),
    material: "Aircraft-grade brushed aluminum top plate, ABS keycaps",
    weight: "1.1kg",
    waterproof: "Spill-resistant",
    origin: "China",
    sku: "LOG-G512-RGB-KB",
  ),
  ProductModel(
    id: "5",
    type: "Recommended",
    name: "Pro Wireless Gaming Mouse",
    prands: "Razer",
    description:
        "Ultra-lightweight wireless mouse with high-precision optical sensor.",
    image:
        "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80",
    price: 49.50,
    rating: 4.6,
    numrating: 195,
    category: "Electronics",
    onstack: "In Stock",
    stock: 18,
    color: const Color(0xFF00C853),
    material: "Lightweight matte polymer shell, PTFE feet",
    weight: "74g",
    waterproof: "No",
    origin: "Taiwan",
    sku: "RZR-VPR-ULT-WLS",
  ),
  ProductModel(
    id: "6",
    type: "Recommended",
    name: "Leather Laptop Backpack",
    prands: "Samsonite",
    description:
        "Water-resistant, durable travel backpack with USB charging port.",
    image:
        "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    price: 59.99,
    rating: 4.7,
    numrating: 160,
    category: "Accessories",
    onstack: "In Stock",
    stock: 12,
    color: const Color(0xFF4E342E),
    material: "Full-grain PU leather, high-density nylon lining",
    weight: "980g",
    waterproof: "Yes — Water repellent finish",
    origin: "India",
    sku: "SAM-BPK-156-LTH",
  ),
  ProductModel(
    id: "7",
    type: "Recommended",
    name: "Casual Fleece Hoodie",
    prands: "Adidas",
    description: "Soft and warm cotton-blend pullover hoodie for daily wear.",
    image:
        "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&q=80",
    price: 38.00,
    rating: 4.4,
    numrating: 88,
    category: "Clothing",
    onstack: "In Stock",
    stock: 40,
    color: const Color(0xFF757575),
    material: "70% French Terry Cotton, 30% Recycled Polyester",
    weight: "460g",
    waterproof: "No",
    origin: "Cambodia",
    sku: "AD-FLC-HD-GRY",
  ),
  ProductModel(
    id: "8",
    type: "Recommended",
    name: "Stainless Steel Water Bottle",
    prands: "Hydro Flask",
    description: "Vacuum-insulated bottle keeping drinks cold up to 24 hours.",
    image:
        "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80",
    price: 24.99,
    rating: 4.9,
    numrating: 420,
    category: "Sports",
    onstack: "In Stock",
    stock: 50,
    color: const Color(0xFF00ACC1),
    material: "18/8 Food-grade stainless steel",
    weight: "340g",
    waterproof: "100% Leak-proof lid",
    origin: "USA",
    sku: "HF-BTL-24OZ-TRQ",
  ),
  ProductModel(
    id: "201",
    type: "Recommended",
    name: "Old Skool Canvas Sneakers",
    prands: "Vans",
    description: "Classic skate shoes with side stripe and padded collars.",
    image:
        "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80",
    price: 55.00,
    rating: 4.7,
    numrating: 230,
    category: "Shoes",
    onstack: "In Stock",
    stock: 35,
    color: const Color(0xFFB71C1C),
    material: "Heavy canvas, suede trim, signature waffle outsole",
    weight: "390g (size M)",
    waterproof: "No",
    origin: "Vietnam",
    sku: "VN-OSK-CNV-RED",
  ),
  ProductModel(
    id: "202",
    type: "Recommended",
    name: "Fast Wireless Charging Stand",
    prands: "Belkin",
    description:
        "15W wireless stand compatible with iPhone and Android devices.",
    image:
        "https://images.unsplash.com/photo-1586816879360-004f5b0c51e5?w=800&q=80",
    price: 29.99,
    rating: 4.5,
    numrating: 115,
    category: "Electronics",
    onstack: "In Stock",
    stock: 22,
    color: const Color(0xFF263238),
    material: "Matte polycarbonate with non-slip silicone base",
    weight: "165g",
    waterproof: "No",
    origin: "China",
    sku: "BLK-WLS-15W-STD",
  ),
  ProductModel(
    id: "203",
    type: "Recommended",
    name: "Breathable Running Cap",
    prands: "Nike",
    description:
        "Lightweight sweat-wicking athletic cap with adjustable strap.",
    image:
        "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&q=80",
    price: 22.50,
    rating: 4.6,
    numrating: 78,
    category: "Accessories",
    onstack: "In Stock",
    stock: 45,
    color: const Color(0xFF1E88E5),
    material: "100% Dri-FIT Polyester",
    weight: "65g",
    waterproof: "Quick-dry fabric",
    origin: "Indonesia",
    sku: "NK-CAP-DRF-BLU",
  ),
];

// ==================== NEW ARRIVALS ====================
List<ProductModel> newProducts = [
  ProductModel(
    id: "9",
    type: "New Arrival",
    name: "Noise-Cancelling Earbuds",
    prands: "Sony",
    description:
        "Compact true wireless earbuds with immersive sound and long battery.",
    image:
        "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80",
    price: 89.99,
    rating: 4.9,
    numrating: 75,
    category: "Electronics",
    onstack: "In Stock",
    stock: 20,
    color: const Color(0xFF212121),
    material: "Recycled ABS composite, polyurethane ear tips",
    weight: "41g (with case)",
    waterproof: "Yes — IPX4 splash resistant",
    origin: "Malaysia",
    sku: "SNY-EBD-WF1000",
  ),
  ProductModel(
    id: "10",
    type: "New Arrival",
    name: "Magnetic Wireless Power Bank",
    prands: "Anker",
    description:
        "10000mAh fast-charging slim power bank with snap-on magnetic tech.",
    image:
        "https://images.unsplash.com/photo-1609592807963-424a1329a7ea?w=800&q=80",
    price: 34.50,
    rating: 4.6,
    numrating: 50,
    category: "Accessories",
    onstack: "In Stock",
    stock: 35,
    color: const Color(0xFF607D8B),
    material: "Soft-touch silicone shell, Lithium polymer cell",
    weight: "218g",
    waterproof: "No",
    origin: "China",
    sku: "ANK-MAG-PB10K",
  ),
  ProductModel(
    id: "11",
    type: "New Arrival",
    name: "Ultra-Fit Training Shorts",
    prands: "Puma",
    description:
        "Breathable, quick-dry activewear shorts designed for running and gym.",
    image:
        "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&q=80",
    price: 27.99,
    rating: 4.5,
    numrating: 32,
    category: "Clothing",
    onstack: "In Stock",
    stock: 45,
    color: const Color(0xFF1E88E5),
    material: "88% Polyester, 12% Spandex 4-way stretch",
    weight: "150g",
    waterproof: "Hydrophobic quick-dry coating",
    origin: "Vietnam",
    sku: "PM-TRN-SHR-BLU",
  ),
  ProductModel(
    id: "12",
    type: "New Arrival",
    name: "Ergonomic Desk Mat",
    prands: "Logitech",
    description: "Spill-resistant large mouse pad with smooth glide surface.",
    image:
        "https://images.unsplash.com/photo-1616628188506-4ad8c1605335?w=800&q=80",
    price: 19.99,
    rating: 4.8,
    numrating: 95,
    category: "Accessories",
    onstack: "In Stock",
    stock: 60,
    color: const Color(0xFF8E24AA),
    material: "100% Recycled polyester surface, anti-slip rubber base",
    weight: "286g",
    waterproof: "Yes — Spill-resistant coating",
    origin: "China",
    sku: "LOG-DSK-MAT-PRP",
  ),
  ProductModel(
    id: "13",
    type: "New Arrival",
    name: "Minimalist Analog Watch",
    prands: "Fossil",
    description:
        "Sleek stainless steel quartz watch with genuine leather strap.",
    image:
        "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80",
    price: 79.00,
    rating: 4.7,
    numrating: 40,
    category: "Fashion",
    onstack: "In Stock",
    stock: 14,
    color: const Color(0xFFD4AF37),
    material: "316L Stainless steel, Mineral crystal glass",
    weight: "68g",
    waterproof: "Yes — 3 ATM (30m)",
    origin: "Japan",
    sku: "FSL-MIN-WCH-GLD",
  ),
  ProductModel(
    id: "301",
    type: "New Arrival",
    name: "Smart Activity Tracker",
    prands: "Xiaomi",
    description:
        "Full-color AMOLED screen with continuous heart rate and sleep tracking.",
    image:
        "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&q=80",
    price: 44.99,
    rating: 4.7,
    numrating: 64,
    category: "Electronics",
    onstack: "In Stock",
    stock: 28,
    color: const Color(0xFF00E5FF),
    material: "Thermoplastic polyurethane (TPU), tempered glass",
    weight: "24g",
    waterproof: "Yes — 5 ATM waterproof",
    origin: "China",
    sku: "XIA-BND-8-CYN",
  ),
  ProductModel(
    id: "302",
    type: "New Arrival",
    name: "Slim Leather Cardholder",
    prands: "Bellroy",
    description:
        "Compact front-pocket bi-fold card case with quick-pull storage tab.",
    image:
        "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80",
    price: 35.00,
    rating: 4.9,
    numrating: 110,
    category: "Accessories",
    onstack: "In Stock",
    stock: 32,
    color: const Color(0xFF3E2723),
    material: "Environmentally certified top-grain leather",
    weight: "38g",
    waterproof: "No",
    origin: "India",
    sku: "BEL-SLM-CRD-BRN",
  ),
  ProductModel(
    id: "303",
    type: "New Arrival",
    name: "Windbreaker Zip Jacket",
    prands: "The North Face",
    description:
        "Lightweight wind-resistant outdoor coat with secure zip pockets.",
    image:
        "https://images.unsplash.com/photo-1544441893-675973e31985?w=800&q=80",
    price: 85.00,
    rating: 4.8,
    numrating: 52,
    category: "Clothing",
    onstack: "In Stock",
    stock: 20,
    color: const Color(0xFFFFA000),
    material: "WindWall ripstop nylon with DWR finish",
    weight: "240g",
    waterproof: "Yes — Water repellent",
    origin: "Bangladesh",
    sku: "TNF-WND-JKT-YEL",
  ),
];
