// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTU5TrYb2ts0noBVD5JJ0Indy1MbxRjd8',
    appId: '1:354885917293:android:63215bc1541a012338fd64',
    messagingSenderId: '354885917293',
    projectId: 'e-commerce-full-fde4b',
    storageBucket: 'e-commerce-full-fde4b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnqBB8twfpC8aYrAEQcAeQ1vWk-ZTo4ZE',
    appId: '1:354885917293:ios:eb4cd57f8657609038fd64',
    messagingSenderId: '354885917293',
    projectId: 'e-commerce-full-fde4b',
    storageBucket: 'e-commerce-full-fde4b.firebasestorage.app',
    androidClientId: '354885917293-tt9pdcembrf3lldbh7sg88facf9cojl1.apps.googleusercontent.com',
    iosClientId: '354885917293-nh6hhjj7mgc7jb3dg4rsn035nja9ocb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
